# Generated by Django 4.2.23 on 2025-06-30 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobServices', '0003_rename_user_name_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
